export const ACTION_TYPE = {
  TRANSPLANTE: 1,
  ALTERA_FASE_CULTIVO: 2,
  DESCARTE_PLANTA: 3,
  DESCARTE_MUDA: 4,
  ALTERA_LOCAL: 5,
  CREATE_PLANT: 6,
  CREATE_MUDA: 7,
  MATRIZ: 8,
  COLHEITA: 9,
  FINISH_CROP: 10
};
